name: Build

on:
  push:
    branches:
      - main

jobs:
  download-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Download APK
      uses: Yakov5776/gh-apkmirror-dl@v1.1
      with:
        org: 'fidelity-investments'
        repo: 'fidelity-investments'
        version: '3.96'
        bundle: false
        file_name: 'app.apk'

    - name: Install Apktool
      run: |
        curl -L -o /usr/local/bin/apktool "https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool"
        curl -L -o /usr/local/bin/apktool.jar "https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar"
        chmod +x /usr/local/bin/apktool

    - name: Decompile APK
      run: apktool d app.apk -o app

    - name: Patch AndroidManifest.xml
      run: |
          sed -i 's/android:allowBackup="true"/android:allowBackup="false"/' app/AndroidManifest.xml
          sed -i 's/<string name="f_app_name">Fidelity<\/string>/<string name="f_app_name">FidelitySim<\/string>/' app/res/values/strings.xml

    - name: Build APK
      run: apktool b app -o app_patched.apk

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app.apk
        path: app_patched.apk
